[package]
name = "mstools"
version = "0.1.0"
authors = ["Matthieu Sprunck <matthieu@sprunck.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies]
wasm-bindgen = "0.2"
base64 = "0.13"
